---
# tasks file for ansible-role-anyenv

- name: install anyenv
  git:
    repo:    "{{ anyenv_repo }}"
    dest:    "{{ anyenv_root }}"
    version: "{{ anyenv_version }}"
    accept_hostkey: yes
  tags: [anyenv]

- name: add profile
  template:
    src:   anyenv.sh.j2
    dest:  /etc/profile.d/anyenv.sh
    owner: root
    group: root
    mode:  0755
  tags: [anyenv]

- name: init anyenv
  shell: |
    . /etc/profile.d/anyenv.sh
    {{ anyenv_root }}/bin/anyenv install --force-init
  args:
    creates: "{{ anyenv_definition_root }}"
    executable: /bin/bash
  changed_when: false
  tags: [anyenv]

- name: install xxenv
  include: install-xxenv.yml
  loop: "{{ anyenv_install_envs }}"
  loop_control:
    loop_var: xxenv
    label: "{{ xxenv }}"
  tags: [anyenv]
