---
# tasks file for ansible-role-anyenv

- name: install anyenv
  git:
    repo:    "{{ anyenv_repo }}"
    dest:    "{{ anyenv_root }}"
    version: "{{ anyenv_version }}"
    accept_hostkey: yes
  tags: [anyenv]

- name: add profile
  template:
    src:   anyenv.sh.j2
    dest:  /etc/profile.d/anyenv.sh
    owner: root
    group: root
    mode:  0755
  tags: [anyenv]

- name: force init. for docker?
  shell: /etc/profile.d/anyenv.sh
  changed_when: false
  tags: [anyenv]

- name: install xxenv
  shell: "ANYENV_ROOT={{ anyenv_root }} {{ anyenv_root }}/bin/anyenv install {{ item }}"
  args:
    creates: "{{ anyenv_root }}/envs/{{ item }}"
  changed_when: false
  with_items: "{{ anyenv_install_envs }}"
  tags: [anyenv]

